// Code generated by mockery v2.44.1. DO NOT EDIT.

package os

import mock "github.com/stretchr/testify/mock"

// Mocktimeout is an autogenerated mock type for the timeout type
type Mocktimeout struct {
	mock.Mock
}

type Mocktimeout_Expecter struct {
	mock *mock.Mock
}

func (_m *Mocktimeout) EXPECT() *Mocktimeout_Expecter {
	return &Mocktimeout_Expecter{mock: &_m.Mock}
}

// Timeout provides a mock function with given fields:
func (_m *Mocktimeout) Timeout() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Timeout")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Mocktimeout_Timeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Timeout'
type Mocktimeout_Timeout_Call struct {
	*mock.Call
}

// Timeout is a helper method to define mock.On call
func (_e *Mocktimeout_Expecter) Timeout() *Mocktimeout_Timeout_Call {
	return &Mocktimeout_Timeout_Call{Call: _e.mock.On("Timeout")}
}

func (_c *Mocktimeout_Timeout_Call) Run(run func()) *Mocktimeout_Timeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Mocktimeout_Timeout_Call) Return(_a0 bool) *Mocktimeout_Timeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mocktimeout_Timeout_Call) RunAndReturn(run func() bool) *Mocktimeout_Timeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMocktimeout creates a new instance of Mocktimeout. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktimeout(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mocktimeout {
	mock := &Mocktimeout{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
